enchantments:
  minecraft:sharpness: 5
  minecraft:efficiency: 5
  minecraft:density: 5
  minecraft:swift_sneak: 3
  minecraft:breach: 4
  minecraft:feather_falling: 4
  minecraft:infinity: 1
  minecraft:flame: 1
  minecraft:impaling: 5
  minecraft:protection: 4
  minecraft:knockback: 2
  minecraft:depth_strider: 3
  minecraft:luck_of_the_sea: 3
  minecraft:silk_touch: 1
  minecraft:loyalty: 3
  minecraft:vanishing_curse: 1
  minecraft:fire_protection: 4
  minecraft:channeling: 1
  minecraft:binding_curse: 1
  minecraft:quick_charge: 3
  minecraft:bane_of_arthropods: 5
  minecraft:frost_walker: 2
  minecraft:multishot: 1
  minecraft:projectile_protection: 4
  minecraft:aqua_affinity: 1
  minecraft:soul_speed: 3
  minecraft:wind_burst: 3
  minecraft:looting: 3
  minecraft:smite: 5
  minecraft:piercing: 4
  minecraft:lure: 3
  minecraft:riptide: 3
  minecraft:power: 5
  minecraft:blast_protection: 4
  minecraft:mending: 1
  minecraft:fire_aspect: 2
  minecraft:respiration: 3
  minecraft:thorns: 3
  minecraft:sweeping_edge: 3
  minecraft:punch: 2
  minecraft:fortune: 3
  minecraft:unbreaking: 3
  # Add other enchantments here
  # 自动输出其他插件或数据包注册的附魔
  # 例如:
  # customplugin:custom_enchantment: 3

settings:
  enableMessages: true

messages:
  limitExceeded: "&cYou have exceeded the enchantment limit!"
  configReloaded: "&aEnchantmentLimit configuration reloaded."
  noPermission: "&cYou do not have permission to execute this command."
  pluginDetected: "&aDetected plugin: &e{plugin}"
  bypassEnabled: "&aBypass enabled for this item."
  bypassDisabled: "&cBypass disabled for this item."
